# This workflow will build a package using Maven and then publish it to GitHub packages when a release is created
# For more information see: https://github.com/actions/setup-java/blob/main/docs/advanced-usage.md#apache-maven-with-a-settings-path

name: Run selenium testcases using selenoid server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Start selenoid server
      uses: n-ton4/selenoid-github-action@master
      id: start-selenoid
      continue-on-error: false
      with:
        version: 1.01.1
    
    - name: checkout
      uses: actions/checkout@v2
    - name: run the test
      run: mvn clean test
